name:                eris
version:             0.1.0.0
github:              "emmettng/eris"
license:             BSD3
author:              "Emmett Ng"
maintainer:          "Emmettng@gmail.com"
copyright:           "Copyright (C) 2018 Emmett H. Ng"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/eris#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - unordered-containers
    - bytestring
    - hmatrix                 ## Numeric.LinearAlgebra
    - cassava                 ## For Data.Csv
    - vector                  ## For Data.Vector
    - mtl
    - hashable
    - QuickCheck
#  exposed-modules:
#    Eris.Compute.Similarity


tests:
  eris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eris
    - hspec
    - QuickCheck

#  quick-test:
#    main:               Quick.hs
#    source-dirs:        test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - QuickCheck
